name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.7


    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
          -backend-config="key=${{ secrets.TF_STATE_KEY }}" \
          -backend-config="region=${{ secrets.AWS_REGION }}" \
          -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}" \
          -backend-config="encrypt=true"
      working-directory: ./terraform

    - name: Terraform Format
      run: terraform fmt -check -diff
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -out=tfplan -input=false
        echo "::set-output name=exitcode::$(echo $?)"
      working-directory: ./terraform

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.plan.outputs.exitcode == 0
      run: terraform apply -auto-approve -input=false tfplan
      working-directory: ./terraform

    - name: Upload Terraform State to S3
      run: |
        aws s3 cp terraform.tfstate s3://${{ secrets.TF_STATE_BUCKET }}/${{ secrets.TF_STATE_KEY }} --region ${{ secrets.AWS_REGION }}
      working-directory: ./terraform
