name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.4


    - name: Terraform Init
      run: |
        terraform init 
      working-directory: ./terraform

    - name: Terraform Format
      run: terraform fmt -check -diff
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -out=tfplan -input=false -var-file=var.tfvars
        echo "::set-output name=exitcode::$(echo $?)"
      working-directory: ./terraform

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.plan.outputs.exitcode == 0
      run: terraform apply -auto-approve -input=false tfplan
      working-directory: ./terraform

